language: csharp  
mono: none
dotnet: 3.1
env:
  global:
    - CODECOV_TOKEN: e7f1349f-814c-47d9-a04a-ebeadc751438
before_script:
  - dotnet restore
  - dotnet build --configuration Release
script:  
  - dotnet test --configuration Release --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_script:
  - bash <(curl -s https://codecov.io/bash)