coverage:
  status:
    project:
      default:
        target: auto
        threshold: 3%
    patch: off
  notify:
    gitter:
      default:
        url: "https://webhooks.gitter.im/e/00d5f9c4fa5d8b7f29f3"
        threshold: 0%
ignore:
  - "src/Camelot/**/*"
  - "src/Camelot.Avalonia/**/*"
  - "src/Camelot.DataAccess.Models/*"
  - "src/Camelot.DataAccess.LiteDb/**/*"
  - "src/Camelot.DataAccess/**/*"
  - "src/Camelot.Services.Environment/**/*"
