//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camelot.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Camelot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AboutCamelotTitle {
            get {
                return ResourceManager.GetString("AboutCamelotTitle", resourceCulture);
            }
        }
        
        public static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        public static string AboutPage {
            get {
                return ResourceManager.GetString("AboutPage", resourceCulture);
            }
        }
        
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        public static string ApplyActionToTheAllFilesAndFolders {
            get {
                return ResourceManager.GetString("ApplyActionToTheAllFilesAndFolders", resourceCulture);
            }
        }
        
        public static string ArgumentsWithColon {
            get {
                return ResourceManager.GetString("ArgumentsWithColon", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string CloseAllButThis {
            get {
                return ResourceManager.GetString("CloseAllButThis", resourceCulture);
            }
        }
        
        public static string CloseTab {
            get {
                return ResourceManager.GetString("CloseTab", resourceCulture);
            }
        }
        
        public static string CloseTabsToTheLeft {
            get {
                return ResourceManager.GetString("CloseTabsToTheLeft", resourceCulture);
            }
        }
        
        public static string CloseTabsToTheRight {
            get {
                return ResourceManager.GetString("CloseTabsToTheRight", resourceCulture);
            }
        }
        
        public static string CommandWithColon {
            get {
                return ResourceManager.GetString("CommandWithColon", resourceCulture);
            }
        }
        
        public static string ConfigurationHeader {
            get {
                return ResourceManager.GetString("ConfigurationHeader", resourceCulture);
            }
        }
        
        public static string CopiedFileFromTo {
            get {
                return ResourceManager.GetString("CopiedFileFromTo", resourceCulture);
            }
        }
        
        public static string CopiedFilesFromAndDirectoriesTo {
            get {
                return ResourceManager.GetString("CopiedFilesFromAndDirectoriesTo", resourceCulture);
            }
        }
        
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        public static string CopyingFileFromTo {
            get {
                return ResourceManager.GetString("CopyingFileFromTo", resourceCulture);
            }
        }
        
        public static string CopyingFilesFromAndDirectoriesTo {
            get {
                return ResourceManager.GetString("CopyingFilesFromAndDirectoriesTo", resourceCulture);
            }
        }
        
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        public static string CreateDirectoryTitle {
            get {
                return ResourceManager.GetString("CreateDirectoryTitle", resourceCulture);
            }
        }
        
        public static string CreationDateWithColon {
            get {
                return ResourceManager.GetString("CreationDateWithColon", resourceCulture);
            }
        }
        
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string DeletedFileFromTo {
            get {
                return ResourceManager.GetString("DeletedFileFromTo", resourceCulture);
            }
        }
        
        public static string DeletedFilesAndDirectories {
            get {
                return ResourceManager.GetString("DeletedFilesAndDirectories", resourceCulture);
            }
        }
        
        public static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        public static string DirectoryInformationTitle {
            get {
                return ResourceManager.GetString("DirectoryInformationTitle", resourceCulture);
            }
        }
        
        public static string DirectoryTemplate {
            get {
                return ResourceManager.GetString("DirectoryTemplate", resourceCulture);
            }
        }
        
        public static string EnterDirectoryNameWithColon {
            get {
                return ResourceManager.GetString("EnterDirectoryNameWithColon", resourceCulture);
            }
        }
        
        public static string ExitHeader {
            get {
                return ResourceManager.GetString("ExitHeader", resourceCulture);
            }
        }
        
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        public static string FailedCopyFileFromTo {
            get {
                return ResourceManager.GetString("FailedCopyFileFromTo", resourceCulture);
            }
        }
        
        public static string FailedCopyFromFilesAndDirectoriesTo {
            get {
                return ResourceManager.GetString("FailedCopyFromFilesAndDirectoriesTo", resourceCulture);
            }
        }
        
        public static string FailedToDeleteFileFromTo {
            get {
                return ResourceManager.GetString("FailedToDeleteFileFromTo", resourceCulture);
            }
        }
        
        public static string FailedToDeleteFilesAndDirectoriesFrom {
            get {
                return ResourceManager.GetString("FailedToDeleteFilesAndDirectoriesFrom", resourceCulture);
            }
        }
        
        public static string FailedToMoveFileFromTo {
            get {
                return ResourceManager.GetString("FailedToMoveFileFromTo", resourceCulture);
            }
        }
        
        public static string FailedToMoveFilesAndDirectoriesTo {
            get {
                return ResourceManager.GetString("FailedToMoveFilesAndDirectoriesTo", resourceCulture);
            }
        }
        
        public static string FileHeader {
            get {
                return ResourceManager.GetString("FileHeader", resourceCulture);
            }
        }
        
        public static string FileInformationTitle {
            get {
                return ResourceManager.GetString("FileInformationTitle", resourceCulture);
            }
        }
        
        public static string FilesRemovingConfirmationTitle {
            get {
                return ResourceManager.GetString("FilesRemovingConfirmationTitle", resourceCulture);
            }
        }
        
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        public static string Github {
            get {
                return ResourceManager.GetString("Github", resourceCulture);
            }
        }
        
        public static string HelpHeader {
            get {
                return ResourceManager.GetString("HelpHeader", resourceCulture);
            }
        }
        
        public static string LanguageWithColon {
            get {
                return ResourceManager.GetString("LanguageWithColon", resourceCulture);
            }
        }
        
        public static string LastAccessWithColon {
            get {
                return ResourceManager.GetString("LastAccessWithColon", resourceCulture);
            }
        }
        
        public static string LastModificationWithColon {
            get {
                return ResourceManager.GetString("LastModificationWithColon", resourceCulture);
            }
        }
        
        public static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        public static string Maintainers {
            get {
                return ResourceManager.GetString("Maintainers", resourceCulture);
            }
        }
        
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        public static string MovedFileFromTo {
            get {
                return ResourceManager.GetString("MovedFileFromTo", resourceCulture);
            }
        }
        
        public static string MovedFilesFromAndDirectoriesTo {
            get {
                return ResourceManager.GetString("MovedFilesFromAndDirectoriesTo", resourceCulture);
            }
        }
        
        public static string MovingFileFromTo {
            get {
                return ResourceManager.GetString("MovingFileFromTo", resourceCulture);
            }
        }
        
        public static string MovingFromFilesAndDirectoriesTo {
            get {
                return ResourceManager.GetString("MovingFromFilesAndDirectoriesTo", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string NewDirectory {
            get {
                return ResourceManager.GetString("NewDirectory", resourceCulture);
            }
        }
        
        public static string NewTab {
            get {
                return ResourceManager.GetString("NewTab", resourceCulture);
            }
        }
        
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        public static string OriginalFile {
            get {
                return ResourceManager.GetString("OriginalFile", resourceCulture);
            }
        }
        
        public static string OverwriteOptionsTitle {
            get {
                return ResourceManager.GetString("OverwriteOptionsTitle", resourceCulture);
            }
        }
        
        public static string PathWithColon {
            get {
                return ResourceManager.GetString("PathWithColon", resourceCulture);
            }
        }
        
        public static string PermanentlyRemoveFiles {
            get {
                return ResourceManager.GetString("PermanentlyRemoveFiles", resourceCulture);
            }
        }
        
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        public static string RemovingFileFromTo {
            get {
                return ResourceManager.GetString("RemovingFileFromTo", resourceCulture);
            }
        }
        
        public static string RemovingFilesAndDirectoriesFrom {
            get {
                return ResourceManager.GetString("RemovingFilesAndDirectoriesFrom", resourceCulture);
            }
        }
        
        public static string RemovingFilesToTrash {
            get {
                return ResourceManager.GetString("RemovingFilesToTrash", resourceCulture);
            }
        }
        
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }
        
        public static string ReplaceFile {
            get {
                return ResourceManager.GetString("ReplaceFile", resourceCulture);
            }
        }
        
        public static string ReplaceFileDestinationDirectory {
            get {
                return ResourceManager.GetString("ReplaceFileDestinationDirectory", resourceCulture);
            }
        }
        
        public static string ReplaceIfOlder {
            get {
                return ResourceManager.GetString("ReplaceIfOlder", resourceCulture);
            }
        }
        
        public static string ReplaceWith {
            get {
                return ResourceManager.GetString("ReplaceWith", resourceCulture);
            }
        }
        
        public static string SelectFromFilesAndDirectories {
            get {
                return ResourceManager.GetString("SelectFromFilesAndDirectories", resourceCulture);
            }
        }
        
        public static string SelectNewNameForDestination {
            get {
                return ResourceManager.GetString("SelectNewNameForDestination", resourceCulture);
            }
        }
        
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        public static string ShowProperties {
            get {
                return ResourceManager.GetString("ShowProperties", resourceCulture);
            }
        }
        
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        public static string SizeWithColon {
            get {
                return ResourceManager.GetString("SizeWithColon", resourceCulture);
            }
        }
        
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        public static string Terminal {
            get {
                return ResourceManager.GetString("Terminal", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string SearchForFilesAndDirectories {
            get {
                return ResourceManager.GetString("SearchForFilesAndDirectories", resourceCulture);
            }
        }
        
        public static string InvalidRegex {
            get {
                return ResourceManager.GetString("InvalidRegex", resourceCulture);
            }
        }
        
        public static string TotalSpaceWithColon {
            get {
                return ResourceManager.GetString("TotalSpaceWithColon", resourceCulture);
            }
        }
        
        public static string AvailableSpaceWithColon {
            get {
                return ResourceManager.GetString("AvailableSpaceWithColon", resourceCulture);
            }
        }
        
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        public static string CreateFileTitle {
            get {
                return ResourceManager.GetString("CreateFileTitle", resourceCulture);
            }
        }
        
        public static string EnterFileNameWithColon {
            get {
                return ResourceManager.GetString("EnterFileNameWithColon", resourceCulture);
            }
        }
        
        public static string ClickToMount {
            get {
                return ResourceManager.GetString("ClickToMount", resourceCulture);
            }
        }
        
        public static string Pack {
            get {
                return ResourceManager.GetString("Pack", resourceCulture);
            }
        }
        
        public static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        public static string ExtractingArchiveTo {
            get {
                return ResourceManager.GetString("ExtractingArchiveTo", resourceCulture);
            }
        }
        
        public static string PackingFilesAndDirectoriesTo {
            get {
                return ResourceManager.GetString("PackingFilesAndDirectoriesTo", resourceCulture);
            }
        }
        
        public static string PackingFileTo {
            get {
                return ResourceManager.GetString("PackingFileTo", resourceCulture);
            }
        }
        
        public static string ExtractedArchiveTo {
            get {
                return ResourceManager.GetString("ExtractedArchiveTo", resourceCulture);
            }
        }
        
        public static string PackedFileTo {
            get {
                return ResourceManager.GetString("PackedFileTo", resourceCulture);
            }
        }
        
        public static string PackedFilesAndDirectoriesTo {
            get {
                return ResourceManager.GetString("PackedFilesAndDirectoriesTo", resourceCulture);
            }
        }
        
        public static string ExtractArchiveHere {
            get {
                return ResourceManager.GetString("ExtractArchiveHere", resourceCulture);
            }
        }
        
        public static string ExtractArchiveToNewDirectory {
            get {
                return ResourceManager.GetString("ExtractArchiveToNewDirectory", resourceCulture);
            }
        }
        
        public static string SelectDirectoryForExtraction {
            get {
                return ResourceManager.GetString("SelectDirectoryForExtraction", resourceCulture);
            }
        }
        
        public static string PackFilesTitle {
            get {
                return ResourceManager.GetString("PackFilesTitle", resourceCulture);
            }
        }
        
        public static string PackToTheFileWithColon {
            get {
                return ResourceManager.GetString("PackToTheFileWithColon", resourceCulture);
            }
        }
        
        public static string CreateArchive {
            get {
                return ResourceManager.GetString("CreateArchive", resourceCulture);
            }
        }
        
        public static string FailedToExtractArchiveTo {
            get {
                return ResourceManager.GetString("FailedToExtractArchiveTo", resourceCulture);
            }
        }
        
        public static string FailedToPackTo {
            get {
                return ResourceManager.GetString("FailedToPackTo", resourceCulture);
            }
        }
        
        public static string FailedToPackFilesAndDirectoriesTo {
            get {
                return ResourceManager.GetString("FailedToPackFilesAndDirectoriesTo", resourceCulture);
            }
        }
        
        public static string OpenWith {
            get {
                return ResourceManager.GetString("OpenWith", resourceCulture);
            }
        }
        
        public static string OpenWithTitle {
            get {
                return ResourceManager.GetString("OpenWithTitle", resourceCulture);
            }
        }
        
        public static string OpeningFiles {
            get {
                return ResourceManager.GetString("OpeningFiles", resourceCulture);
            }
        }
        
        public static string RecommendedApplications {
            get {
                return ResourceManager.GetString("RecommendedApplications", resourceCulture);
            }
        }
        
        public static string SelectOtherApplications {
            get {
                return ResourceManager.GetString("SelectOtherApplications", resourceCulture);
            }
        }
        
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        public static string SetAsDefaultApplication {
            get {
                return ResourceManager.GetString("SetAsDefaultApplication", resourceCulture);
            }
        }
        
        public static string SearchForApplications {
            get {
                return ResourceManager.GetString("SearchForApplications", resourceCulture);
            }
        }
        
        public static string EnterNewNameWithColon {
            get {
                return ResourceManager.GetString("EnterNewNameWithColon", resourceCulture);
            }
        }
        
        public static string ThemeWithColon {
            get {
                return ResourceManager.GetString("ThemeWithColon", resourceCulture);
            }
        }
        
        public static string DarkThemeName {
            get {
                return ResourceManager.GetString("DarkThemeName", resourceCulture);
            }
        }
        
        public static string LightThemeName {
            get {
                return ResourceManager.GetString("LightThemeName", resourceCulture);
            }
        }
    }
}
