//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camelot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Camelot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Camelot.
        /// </summary>
        public static string ABOUT_CAMELOT_TITLE {
            get {
                return ResourceManager.GetString("ABOUT_CAMELOT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camelot is dual-panel file manager written in C#.
        /// </summary>
        public static string ABOUT_PAGE {
            get {
                return ResourceManager.GetString("ABOUT_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string APPLY {
            get {
                return ResourceManager.GetString("APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply this action to the all files and folders.
        /// </summary>
        public static string APPLY_ACTION_FOR_ALL_FILES_AND_FOLDERS {
            get {
                return ResourceManager.GetString("APPLY_ACTION_FOR_ALL_FILES_AND_FOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all but this.
        /// </summary>
        public static string CLOSE_All_BUT_THIS {
            get {
                return ResourceManager.GetString("CLOSE_All_BUT_THIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tab.
        /// </summary>
        public static string CLOSE_TAB {
            get {
                return ResourceManager.GetString("CLOSE_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tabs to the left.
        /// </summary>
        public static string CLOSE_TABS_TO_THE_LEFT {
            get {
                return ResourceManager.GetString("CLOSE_TABS_TO_THE_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tabs to the right.
        /// </summary>
        public static string CLOSE_TABS_TO_THE_RIGHT {
            get {
                return ResourceManager.GetString("CLOSE_TABS_TO_THE_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string COPY {
            get {
                return ResourceManager.GetString("COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create directory.
        /// </summary>
        public static string CREATE_DIRECTORY_TITLE {
            get {
                return ResourceManager.GetString("CREATE_DIRECTORY_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string CREATION_DATE {
            get {
                return ResourceManager.GetString("CREATION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory information.
        /// </summary>
        public static string DIRECTORY_INFORMATION_TITLE {
            get {
                return ResourceManager.GetString("DIRECTORY_INFORMATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter directory name.
        /// </summary>
        public static string ENTER_DIRECTORY_NAME {
            get {
                return ResourceManager.GetString("ENTER_DIRECTORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File information.
        /// </summary>
        public static string FILE_INFORMATION_TITLE {
            get {
                return ResourceManager.GetString("FILE_INFORMATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files removing confirmation.
        /// </summary>
        public static string FILES_REMOVING_CONFIRMATION_TITLE {
            get {
                return ResourceManager.GetString("FILES_REMOVING_CONFIRMATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        public static string GITHUB {
            get {
                return ResourceManager.GetString("GITHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last access.
        /// </summary>
        public static string LAST_ACCESS {
            get {
                return ResourceManager.GetString("LAST_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modification.
        /// </summary>
        public static string LAST_MODIFICATION {
            get {
                return ResourceManager.GetString("LAST_MODIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified.
        /// </summary>
        public static string LAST_MODIFIED {
            get {
                return ResourceManager.GetString("LAST_MODIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintainers.
        /// </summary>
        public static string MAINTENERS {
            get {
                return ResourceManager.GetString("MAINTENERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string MOVE {
            get {
                return ResourceManager.GetString("MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Directory.
        /// </summary>
        public static string NEW_DIRECTORY {
            get {
                return ResourceManager.GetString("NEW_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tab.
        /// </summary>
        public static string NEW_TAB {
            get {
                return ResourceManager.GetString("NEW_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OPEN {
            get {
                return ResourceManager.GetString("OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original file.
        /// </summary>
        public static string ORIGIN_FILE {
            get {
                return ResourceManager.GetString("ORIGIN_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite options.
        /// </summary>
        public static string OVERWRITE_OPTIONS_TITLE {
            get {
                return ResourceManager.GetString("OVERWRITE_OPTIONS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string PATH {
            get {
                return ResourceManager.GetString("PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to permanently remove these {0} files?.
        /// </summary>
        public static string PERMAMENTLY_REMOVE {
            get {
                return ResourceManager.GetString("PERMAMENTLY_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string REMOVE {
            get {
                return ResourceManager.GetString("REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove these {0} files to trash?.
        /// </summary>
        public static string REMOVING_TO_TRASH {
            get {
                return ResourceManager.GetString("REMOVING_TO_TRASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string RENAME {
            get {
                return ResourceManager.GetString("RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string REPLACE {
            get {
                return ResourceManager.GetString("REPLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace file.
        /// </summary>
        public static string REPLACE_FILE {
            get {
                return ResourceManager.GetString("REPLACE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another file with the same name already exists in &quot;{0}&quot; Do you want to replace it?.
        /// </summary>
        public static string REPLACE_FILE_DESTINATION_DIRECTORY {
            get {
                return ResourceManager.GetString("REPLACE_FILE_DESTINATION_DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace if older.
        /// </summary>
        public static string REPLACE_IF_FOLDER {
            get {
                return ResourceManager.GetString("REPLACE_IF_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with.
        /// </summary>
        public static string REPLACE_WITH {
            get {
                return ResourceManager.GetString("REPLACE_WITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new name for the destination.
        /// </summary>
        public static string SELECT_NEW_NAME_FOR_DESTINATION {
            get {
                return ResourceManager.GetString("SELECT_NEW_NAME_FOR_DESTINATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SETTINGS_TITLE {
            get {
                return ResourceManager.GetString("SETTINGS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string SIZE {
            get {
                return ResourceManager.GetString("SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string SKIP {
            get {
                return ResourceManager.GetString("SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal.
        /// </summary>
        public static string TERMINAL {
            get {
                return ResourceManager.GetString("TERMINAL", resourceCulture);
            }
        }
    }
}
